print("Bitte geben Sie ein Symbol ein:")
symbol = input()
print("Ihr persönliches Dreieck:")
print(symbol)
print(2 * symbol)
print(3 * symbol)
print(4 * symbol)
print(5 * symbol)
print(6 * symbol)
print(7 * symbol)
print(8 * symbol)
print(9 * symbol)
print(10 * symbol)
