import turtle

turtle.left(90)
turtle.forward(100)
turtle.backward(50)
turtle.right(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(50)
turtle.backward(100)
turtle.right(90)
turtle.penup()
turtle.forward(40)
turtle.pendown()
turtle.left(90)
turtle.forward(50)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(20)
